# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exports_files(
    srcs = [
        "rvv_backend_alu.svh",
        "rvv_backend_define.svh",
        "rvv_backend_div.svh",
        "rvv_backend_config.svh",
        "rvv_backend_dispatch.svh",
        "rvv_backend_pmtrdt.svh",
        "rvv_backend.svh",
        "rvv_backend_sva.svh"
    ],
    visibility = ["//visibility:public"],
)