# Clock Signal
create_clock -period 10.00 -name sys_clk_pin -waveform {0 5} [get_ports clk_p_i]
set_property -dict { PACKAGE_PIN U13 IOSTANDARD DIFF_SSTL18_I } [get_ports { clk_p_i }];
set_property -dict { PACKAGE_PIN T13 IOSTANDARD DIFF_SSTL18_I } [get_ports { clk_n_i }];
create_clock -period 6.4 -name c0_sys_clk_p [get_ports c0_sys_clk_p]

# Generated Clocks
create_generated_clock -name clk_main [get_pin i_clkgen/i_clkgen/pll/CLKOUT0]
create_generated_clock -name clk_48MHz [get_pin i_clkgen/i_clkgen/pll/CLKOUT1]
create_generated_clock -name clk_aon [get_pin i_clkgen/i_clkgen/pll/CLKOUT4]

# Reset
set_property -dict { PACKAGE_PIN AR19 IOSTANDARD LVCMOS18 } [get_ports { rst_ni }];

# SPI
create_clock -period 83.333 -name spi_clk_i -waveform {0 41.667} [get_ports spi_clk_i]
set_property -dict { PACKAGE_PIN AV19 IOSTANDARD LVCMOS18 } [get_ports { spi_clk_i }];
set_property -dict { PACKAGE_PIN AW20 IOSTANDARD LVCMOS18 } [get_ports { spi_csb_i }];
set_property -dict { PACKAGE_PIN AV20 IOSTANDARD LVCMOS18 } [get_ports { spi_mosi_i }];
set_property -dict { PACKAGE_PIN AV18 IOSTANDARD LVCMOS18 } [get_ports { spi_miso_o }];

# UART0
set_property -dict { PACKAGE_PIN BF20 IOSTANDARD LVCMOS18 } [get_ports { uart_tx_o[0] }];
set_property -dict { PACKAGE_PIN BD20 IOSTANDARD LVCMOS18 } [get_ports { uart_rx_i[0] }];

# UART1
set_property -dict { PACKAGE_PIN R23 IOSTANDARD LVCMOS18 } [get_ports { uart_tx_o[1] }];
set_property -dict { PACKAGE_PIN T23 IOSTANDARD LVCMOS18 } [get_ports { uart_rx_i[1] }];

# LEDs
set_property -dict { PACKAGE_PIN T31 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { io_halted }];
set_property -dict { PACKAGE_PIN P31 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { io_fault }];
set_property -dict { PACKAGE_PIN N37 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { ddr_cal_complete_o }];
set_property -dict { PACKAGE_PIN M38 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { io_ddr_mem_axi_aw_ready }];
set_property -dict { PACKAGE_PIN L38 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { io_ddr_mem_axi_ar_ready }];
set_property -dict { PACKAGE_PIN L36 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { ddr_ui_clk }];
set_property -dict { PACKAGE_PIN K36 DRIVE 8 IOSTANDARD LVCMOS12 } [get_ports { ddr_ui_clk_sync_rst }];

# Asynchronous Clock Groups
# Define all primary, asynchronous clocks
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks sys_clk_pin] \
  -group [get_clocks -include_generated_clocks c0_sys_clk_p] \
  -group [get_clocks spi_clk_i]

# SPI Probe Outputs (PMOD3)
set_property -dict { PACKAGE_PIN AU40 IOSTANDARD LVCMOS18 } [get_ports { spi_clk_probe_o }];
set_property -dict { PACKAGE_PIN AV40 IOSTANDARD LVCMOS18 } [get_ports { spi_csb_probe_o }];
set_property -dict { PACKAGE_PIN AW40 IOSTANDARD LVCMOS18 } [get_ports { spi_mosi_probe_o }];
set_property -dict { PACKAGE_PIN AY39 IOSTANDARD LVCMOS18 } [get_ports { spi_miso_probe_o }];

# DDR4
## --- Start of constraints from reference design ---

## Clock constraint for input system clock which drives MMCM for the design

set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[34]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[36]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[35]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[37]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[32]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[33]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[38]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[39]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[26]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[27]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_parity" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[28]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[24]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[25]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_act_n" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_odt[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_odt[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[64]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[65]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[70]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[29]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[30]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_cke[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_cs_n[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[17]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[17]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[66]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[67]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[71]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[31]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_cke[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_cs_n[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[68]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[69]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[16]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[16]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[56]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[16]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[17]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_bg[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_ba[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_bg[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[16]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[58]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[59]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[57]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[18]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_ba[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[62]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[63]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[19]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[22]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[13]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[60]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[61]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[48]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[49]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[20]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[21]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[23]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[6]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[46]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[47]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[50]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[54]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[8]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[14]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[4]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[7]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[11]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[40]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[52]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[51]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[55]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[9]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[15]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[3]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[0]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_adr[5]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[44]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[41]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[53]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_t[13]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[13]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports "c0_ddr4_ck_t[0]" ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports "c0_ddr4_ck_c[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[1]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[45]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[42]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[43]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[13]" ]

set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[34]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[36]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[35]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[8]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[37]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[8]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[3]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[32]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[33]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[38]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[39]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[26]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[9]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[9]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[1]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[27]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[6]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[6]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[6]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[7]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_parity" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[5]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[28]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[24]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[25]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_act_n" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_odt[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_odt[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[64]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[65]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[70]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[29]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[30]" ]
set_property IOSTANDARD LVCMOS12 [ get_ports "c0_ddr4_reset_n" ]
set_property DRIVE 8 [ get_ports "c0_ddr4_reset_n" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_cke[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_cs_n[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[17]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[17]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[66]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[67]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[71]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[7]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[7]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[31]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_cke[1]" ]
set_property IOSTANDARD DIFF_SSTL12 [ get_ports "c0_sys_clk_p" ]
set_property IOSTANDARD DIFF_SSTL12 [ get_ports "c0_sys_clk_n" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_cs_n[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[68]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[69]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[16]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[16]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[56]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[16]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[17]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_bg[1]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_ba[1]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_bg[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[16]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[15]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[58]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[59]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[57]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[18]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[5]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[14]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[15]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[12]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_ba[0]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[14]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[14]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[15]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[62]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[63]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[4]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[19]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[22]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[5]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[10]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[11]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[13]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[60]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[61]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[48]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[49]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[20]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[21]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[23]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[8]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[6]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[46]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[47]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[50]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[54]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[10]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[8]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[14]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[2]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[9]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[4]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[7]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[11]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[40]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[52]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[51]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[55]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[9]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[15]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[3]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[5]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[44]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[10]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[41]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[53]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[12]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_t[13]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[12]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[13]" ]
set_property IOSTANDARD DIFF_POD12_DCI [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports "c0_ddr4_ck_t[0]" ]
set_property IOSTANDARD DIFF_SSTL12_DCI [ get_ports "c0_ddr4_ck_c[0]" ]
set_property IOSTANDARD SSTL12_DCI [ get_ports "c0_ddr4_adr[1]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[42]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[43]" ]
set_property IOSTANDARD POD12_DCI [ get_ports "c0_ddr4_dq[45]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[10]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[42]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dq[43]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[12]" ]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [ get_ports "c0_ddr4_dqs_c[13]" ]



set_property SLEW FAST  [get_ports {c0_ddr4_adr[*] c0_ddr4_act_n c0_ddr4_ba[*] c0_ddr4_bg[*] c0_ddr4_cke[*] c0_ddr4_ck_t[*] c0_ddr4_ck_c[*] c0_ddr4_odt[*] c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*]}]
set_property IBUF_LOW_PWR FALSE  [get_ports {c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*]}]
set_property ODT RTT_60  [get_ports {c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*]}]
set_property EQUALIZATION EQ_LEVEL3 [get_ports {c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*]}]
set_property SLEW FAST  [get_ports {c0_ddr4_parity}]
set_property DATA_RATE SDR  [get_ports {c0_ddr4_parity}]
set_property SLEW FAST  [get_ports {c0_ddr4_cs_n[*]}]
set_property DATA_RATE SDR  [get_ports {c0_ddr4_cs_n[*]}]
set_property DATA_RATE SDR  [get_ports {c0_ddr4_adr[*] c0_ddr4_act_n c0_ddr4_ba[*] c0_ddr4_bg[*] c0_ddr4_cke[*] c0_ddr4_odt[*] }]
set_property DATA_RATE DDR  [get_ports {c0_ddr4_dq[*] c0_ddr4_dqs_t[*] c0_ddr4_dqs_c[*] c0_ddr4_ck_t[*] c0_ddr4_ck_c[*]}]

## Multi-cycle path constraints for Fabric - RIU clock domain crossing signals
set_max_delay 5.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/u_ddr_cal_addr_decode/io_ready_lvl_reg/C] -to [get_pins i_ddr4/inst/*/u_io_ready_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 5.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/u_ddr_cal_addr_decode/io_read_data_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_io_read_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/phy_ready_riuclk_reg/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_phy_ready_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/bisc_complete_riuclk_reg/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_bisc_complete_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/io_addr_strobe_lvl_riuclk_reg/C] -to [get_pins i_ddr4/inst/*/u_io_addr_strobe_lvl_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/io_write_strobe_riuclk_reg/C] -to [get_pins i_ddr4/inst/*/u_io_write_strobe_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/io_address_riuclk_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_io_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/io_write_data_riuclk_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_io_write_data_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/en_vtc_in_reg/C] -to [get_pins i_ddr4/inst/*/u_en_vtc_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/riu2clb_valid_r1_riuclk_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_riu2clb_valid_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/phy2clb_fixdly_rdy_low_riuclk_int_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_fixdly_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/phy2clb_fixdly_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_fixdly_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/phy2clb_phy_rdy_low_riuclk_int_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_phy_rdy_low/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/phy2clb_phy_rdy_upp_riuclk_int_reg[*]/C] -to [get_pins i_ddr4/inst/*/u_phy2clb_phy_rdy_upp/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 10.0 -datapath_only -from [get_pins i_ddr4/inst/*/rst_r1_reg/C] -to [get_pins i_ddr4/inst/*/u_fab_rst_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/clb2phy_t_b_addr_riuclk_reg/C] -to [get_pins  i_ddr4/inst/*/*/*/clb2phy_t_b_addr_i_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/*/slave_en_lvl_reg/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_en_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/*/slave_we_r_reg/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_we_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/*/slave_addr_r_reg[*]/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_addr_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/*/slave_di_r_reg[*]/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_di_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 3.0 -datapath_only -from [get_pins  i_ddr4/inst/*/*/*/*/slave_rdy_cptd_sclk_reg/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_rdy_cptd_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 12.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/*/slave_rdy_lvl_fclk_reg/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_rdy_sync/SYNC[*].sync_reg_reg[0]/D]
set_max_delay 12.0 -datapath_only -from [get_pins i_ddr4/inst/*/*/*/*/slave_do_fclk_reg[*]/C] -to [get_pins  i_ddr4/inst/*/*/*/*/u_slave_do_sync/SYNC[*].sync_reg_reg[0]/D]

set_false_path -through [get_pins i_ddr4/inst/u_ddr4_infrastructure/sys_rst]
set_false_path -from [get_pins  i_ddr4/inst/*/input_rst_design_reg/C] -to [get_pins i_ddr4/inst/*/rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  i_ddr4/inst/*/input_rst_design_reg/C] -to [get_pins i_ddr4/inst/*/rst_riu_sync_r_reg[0]/D]
set_false_path -from [get_pins  i_ddr4/inst/*/input_rst_design_reg/C] -to [get_pins i_ddr4/inst/*/rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  i_ddr4/inst/*/rst_async_riu_div_reg/C] -to [get_pins i_ddr4/inst/*/rst_div_sync_r_reg[0]/D]
set_false_path -from [get_pins  i_ddr4/inst/*/rst_async_mb_reg/C]      -to [get_pins i_ddr4/inst/*/rst_mb_sync_r_reg[0]/D]
set_false_path -from [get_pins  i_ddr4/inst/*/rst_async_riu_div_reg/C] -to [get_pins i_ddr4/inst/*/rst_riu_sync_r_reg[0]/D]

create_waiver -internal -user DDR4 -tags "1010162" -scope -type METHODOLOGY -id CLKC-55 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "i_ddr4/inst/*gen_mmcme*.u_mmcme_adv_inst*" -filter {NAME =~ *inst/u_ddr4_infrastructure*}]
create_waiver -internal -user DDR4 -tags "1010162" -scope -type METHODOLOGY -id CLKC-56 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "i_ddr4/inst/*gen_mmcme*.u_mmcme_adv_inst*" -filter {NAME =~ *inst/u_ddr4_infrastructure*}]
create_waiver -internal -user DDR4 -tags "1010162" -scope -type METHODOLOGY -id CLKC-57 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "i_ddr4/inst/*plle_loop[*].gen_plle*.PLLE*_BASE_INST_OTHER*" -filter {NAME =~ *inst/u_ddr4_phy_pll*}]
create_waiver -internal -user DDR4 -tags "1010162" -scope -type METHODOLOGY -id CLKC-58 -description "Clocking Primitives will be Auto-Placed" -objects [get_cells -hierarchical "i_ddr4/inst/*plle_loop[*].gen_plle*.PLLE*_BASE_INST_OTHER*" -filter {NAME =~ *inst/u_ddr4_phy_pll*}]
create_waiver -internal -user DDR4 -tags "1010162" -scope -type METHODOLOGY -id CLKC-40 -description "MMCM is driven through a BUFGCE" -objects [get_cells -hierarchical "i_ddr4/inst/*gen_mmcme*.u_mmcme_adv_inst*" -filter {NAME =~ *inst/u_ddr4_infrastructure*}]

## --- End of constraints from reference design ---

## Bank 71
set_property PACKAGE_PIN T26                [get_ports {c0_ddr4_odt[1]}]
set_property PACKAGE_PIN T24                [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN R24                [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN P27                [get_ports {c0_ddr4_cs_n[1]}]
set_property PACKAGE_PIN M28                [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN M25                [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN L26                [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN L28                [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN K28                [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN L24                [get_ports {c0_ddr4_parity}]
set_property PACKAGE_PIN L25                [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN K26                [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN J26                [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN J27                [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN G26                [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN F26                [get_ports c0_sys_clk_n]
set_property PACKAGE_PIN F28                [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN E28                [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN H28                [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN G28                [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN E26                [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN E27                [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN G25                [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN F25                [get_ports {c0_ddr4_cke[1]}]
set_property PACKAGE_PIN D27                [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN C28                [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN B28                [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN A28                [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN C27                [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN B27                [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN B26                [get_ports {c0_ddr4_bg[1]}]
set_property PACKAGE_PIN A26                [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN C25                [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN B25                [get_ports {c0_ddr4_cke[0]}]

## Bank 70
set_property PACKAGE_PIN R28                [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN R29                [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN M31                [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN L31                [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN P29                [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN P30                [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN N30                [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN M30                [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN N28                [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN N29                [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN L29                [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN L30                [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN K31                [get_ports {c0_ddr4_dqs_t[13]}]
set_property PACKAGE_PIN J31                [get_ports {c0_ddr4_dqs_c[13]}]
set_property PACKAGE_PIN K32                [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN J32                [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN J29                [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN J30                [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN H33                [get_ports {c0_ddr4_dqs_t[12]}]
set_property PACKAGE_PIN G33                [get_ports {c0_ddr4_dqs_c[12]}]
set_property PACKAGE_PIN H29                [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN H30                [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN H32                [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN G32                [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN G31                [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN F31                [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN G30                [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN F30                [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN F33                [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN E33                [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN E31                [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN D31                [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN E32                [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN D32                [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN F29                [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN E29                [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN C32                [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN C33                [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN B31                [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN B32                [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN B33                [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN A33                [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN A30                [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN A31                [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN C30                [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN B30                [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN D29                [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN C29                [get_ports {c0_ddr4_dq[17]}]

## Bank 69
set_property PACKAGE_PIN J39                [get_ports {c0_ddr4_dqs_t[16]}]
set_property PACKAGE_PIN J40                [get_ports {c0_ddr4_dqs_c[16]}]
set_property PACKAGE_PIN H39                [get_ports {c0_ddr4_dq[65]}]
set_property PACKAGE_PIN H40                [get_ports {c0_ddr4_dq[67]}]
set_property PACKAGE_PIN G40                [get_ports {c0_ddr4_dq[66]}]
set_property PACKAGE_PIN F40                [get_ports {c0_ddr4_dq[64]}]
set_property PACKAGE_PIN H38                [get_ports {c0_ddr4_dqs_t[17]}]
set_property PACKAGE_PIN G38                [get_ports {c0_ddr4_dqs_c[17]}]
set_property PACKAGE_PIN K37                [get_ports {c0_ddr4_dq[71]}]
set_property PACKAGE_PIN J37                [get_ports {c0_ddr4_dq[70]}]
set_property PACKAGE_PIN F38                [get_ports {c0_ddr4_dq[68]}]
set_property PACKAGE_PIN F39                [get_ports {c0_ddr4_dq[69]}]
set_property PACKAGE_PIN F34                [get_ports {c0_ddr4_dqs_t[11]}]
set_property PACKAGE_PIN E34                [get_ports {c0_ddr4_dqs_c[11]}]
set_property PACKAGE_PIN J35                [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN H35                [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN J36                [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN H37                [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN H34                [get_ports {c0_ddr4_dqs_t[10]}]
set_property PACKAGE_PIN G35                [get_ports {c0_ddr4_dqs_c[10]}]
set_property PACKAGE_PIN F35                [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN F36                [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN G36                [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN G37                [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN E39                [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN D39                [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN E37                [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN E38                [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN C39                [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN B40                [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN A39                [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN A40                [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN D40                [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN C40                [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN B38                [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN A38                [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN D37                [get_ports {c0_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN C37                [get_ports {c0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN D35                [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN C35                [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN D34                [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN C34                [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN B36                [get_ports {c0_ddr4_dqs_t[9]}]
set_property PACKAGE_PIN B37                [get_ports {c0_ddr4_dqs_c[9]}]
set_property PACKAGE_PIN B35                [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN A36                [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN A34                [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN A35                [get_ports {c0_ddr4_dq[36]}]

## Bank 68
set_property PACKAGE_PIN L34                [get_ports {c0_ddr4_dqs_t[15]}]
set_property PACKAGE_PIN K34                [get_ports {c0_ddr4_dqs_c[15]}]
set_property PACKAGE_PIN N34                [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN N35                [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN L33                [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN K33                [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN N33                [get_ports {c0_ddr4_dqs_t[14]}]
set_property PACKAGE_PIN M33                [get_ports {c0_ddr4_dqs_c[14]}]
set_property PACKAGE_PIN N32                [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN M32                [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN M35                [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN L35                [get_ports {c0_ddr4_dq[56]}]
