#!/bin/bash --norc
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PROG=$(basename "$0")
DRIVER_DIR=$(dirname "$0")
TOOLCHAIN="toolchain_coralnpu_v2"
PREFIX="riscv32-unknown-elf"

LIBMPFR_PATH=$(ldconfig -p | grep 'mpfr.so$' | awk '{print $4}')
WORKDIR=$(mktemp -d)
trap "rm -rf ${WORKDIR}" EXIT
ln -sf ${LIBMPFR_PATH} ${WORKDIR}/libmpfr.so.4

export LD_LIBRARY_PATH=${WORKDIR}:$LD_LIBRARY_PATH
exec "${DRIVER_DIR}/../external/${TOOLCHAIN}/bin/${PREFIX}-gdb" \
    "$@"\
